db.url=jdbc:mysql://localhost:3307/SecurityAccessLite?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
db.user=secureaccess
db.password=secureaccess123